### ISSUE TITLE
hybrid algorithm

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/polonius#100]
As discussed in [today's meeting](https://rust-lang.zulipchat.com/#narrow/stream/186049-t-compiler.2Fwg-polonius/topic/meeting.202019.2E03.2E07), a simple starter issue for getting more understanding of how polonius works is to create a "hybrid" algorithm that first tries the location-insensitive analysis and -- if there are errors -- falls back to datafrog-opt.

**Comment by nikomatsakis** [comment]
In the meeting we said that @matthewjasper would try to write up some mentoring instructions and @albins would try to fix this. =)

**Comment by nikomatsakis** [comment]
[Zulip topic for discussing this issue here](https://rust-lang.zulipchat.com/#narrow/stream/186049-t-compiler.2Fwg-polonius/topic/hybrid.20algorithm.20polonius.23100)

**Comment by matthewjasper** [comment]
To add a new pass first add a new variant to the `Algorithm` enum here: https://github.com/rust-lang/polonius/blob/ecafafba28e4903b9fe7a7df19b87d97541c3c62/polonius-engine/src/output/mod.rs#L20-L51

also use the new pass in `Algorithm::variants` and `Algorithm::from_str`.

Then the new algorithm can be implemented by adding another arm here: https://github.com/rust-lang/polonius/blob/ecafafba28e4903b9fe7a7df19b87d97541c3c62/polonius-engine/src/output/mod.rs#L116-L135

The pass just has to run the location insensitive pass, check if `errors` is non-empty, and if so run the optimized pass. It may be a good idea to have this in its own module so that it doesn't need to be moved when a more complicated hybrid algorithm is created.

Finally, the pass should be tested by adding a test here that runs that hybrid algorithm and asserts that it gets the same errors (only) as the naive algorithm:

https://github.com/rust-lang/polonius/blob/ecafafba28e4903b9fe7a7df19b87d97541c3c62/src/test.rs#L13-L51
